version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: nebenkostenrechner
    main: ./cmd/nebenkostenrechner
    binary: nebenkostenrechner
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.buildDate={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"

archives:
  - id: nebenkostenrechner
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc
  abbrev: 7
  format: >-
    {{ .SHA }} {{ trimprefix (trimprefix (trimprefix (trimprefix (trimprefix .Message "feat: ") "fix: ") "refactor: ") "docs: ") "style: " }}
  filters:
    exclude:
      - "^chore"
      - "^test"
      - "^perf"
      - "^ci"
      - "^build"
      - "^ops"
      - "^docs"
      - "^style"
  groups:
    - title: "Breaking Changes"
      regexp: '(?i)\(BC\)|\bBREAKING CHANGE\b'
      order: 10
    - title: "Experimental Features"
      regexp: '(?i)\(experimental\)'
      order: 25
    - title: "Bug Fixes"
      regexp: '(?i)^fix(\(.+\))?:|\bfix\b'
      order: 30
    - title: "New Features"
      regexp: '(?i)^feat(\(.+\))?:|\badd\b'
      order: 20
    - title: "Refactoring"
      regexp: '(?i)^refactor(\(.+\))?:'
      order: 40
    - title: "Other Changes"
      order: 999

release:
  header: |
    ## Changelog
  github:
    owner: larknafets
    name: nebenkostenrechner
